version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/kousuketk/myDB_go
    steps:
      - checkout
      - run: echo 'Hello world!'

  test:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/kousuketk/myDB_go
    steps:
      - checkout
      - run:
          name: gofmt
          command: test -z "$(gofmt -s -l . | tee /dev/stderr)"
      - run:
          name: go vet
          command: go vet ./...
      - run:
          name: go test -race
          command: go run -race ./...
      - run:
          name: go test
          command: go test test/pkg/btree_test.go -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build